name: telegram message
on:
  push:
    branches:
      - dev
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
      - uses: thedoctor0/zip-release@master
      - uses: ncipollo/release-action@v1
      - uses: appleboy/telegram-action@master
        with:
#          artifacts: "release.tar.gz,foo/*.txt"
#          bodyFile: "body.md"
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: ./release.zip
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

#  notify:
#    runs-on: ubuntu-latest
#    steps:
#      - name: send telegram message on push
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_TO }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          document: ./release.zip
#          message: |
#            ${{ github.actor }} created commit:
#            Commit message: ${{ github.event.commits[0].message }}
#
#            Repository: ${{ github.repository }}
#
#            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
