name: Create release
on:
  push:
    branches:
      - dev

env:
  VERSION_PREFIX: MyPrefix
  VERSION_NAME: ${{ github.event.release.tag_name }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: release-${{ env.VERSION_PREFIX }}.zip
          exclusions: '*.git* /*node_modules/* .editorconfig'
      - name: Notify on telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: ./release-${{ env.VERSION_PREFIX }}.zip
          message: |
            ${{ github.actor }} created release:
            Version: release-${{ env.VERSION_PREFIX }}.zip

